INSERT INTO categories (name) VALUES ('Other');
INSERT INTO categories (name) VALUES ('Technology');
INSERT INTO categories (name) VALUES ('Arts');
INSERT INTO categories (name) VALUES ('TV & Film');
INSERT INTO categories (name) VALUES ('Comedy');
INSERT INTO categories (name) VALUES ('Education');
INSERT INTO categories (name) VALUES ('Science');
INSERT INTO categories (name) VALUES ('Sports');
INSERT INTO categories (name) VALUES ('True Crime');
INSERT INTO categories (name) VALUES ('History');
INSERT INTO categories (name) VALUES ('Health');